spring.application.name=agent-poc-service
server.port=9001

spring.ai.openai.base-url=${OPENAI_URL:https://dashscope.aliyuncs.com/compatible-mode}
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=${OPENAI_CHAT_MODEL:qwen3.5-plus}
app.agent.skills-dir=./skills